version: "3"

services:
  elasticsearch:
    image: elasticsearch:latest
    build: ./elasticsearch
    ports:
      - 9200:9200
  logstash:
    image: logstash:latest
    build: ./logstash
    depends_on:
      - elasticsearch
